import type { Metadata } from 'next'
import { Toaster } from "@/components/ui/sonner";
import { Header } from '@/components/Header';
import './globals.css'

export const metadata: Metadata = {
  title: 'Hono | nextjs',
  description: 'Generated by hono'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <div className="w-full">
          {children}
        </div>
        <Toaster position='top-center'/>
      </body>
    </html>
  )
}
